### ISSUE TITLE
执行onCompleted()之后执行onError()的问题

### ISSUE THREAD

**Issue by ghost** [ysmintor/Retrofit2RxjavaDemo#1]
在没有网络的情况下，会执行下面这段代码
if (!NetworkUtil.isNetworkAvailable(mContext)) {
            Toast.makeText(mContext, "当前无网络，请检查网络情况", Toast.LENGTH_SHORT).show();
            onCompleted();
          //xxx
}
但是我测试下了，接着还会走onError（），我觉得那个方法不应该走啊，没有网络，不应该执行网络请求，所以我觉得应该在 onCompleted();下面在加一段代码
    // if  NetworkAvailable no !   must to call onCompleted
        if (!NetworkUtil.isNetworkAvailable(mContext)) {
            Toast.makeText(mContext, "当前无网络，请检查网络情况", Toast.LENGTH_SHORT).show();
            onCompleted();
            if (!isUnsubscribed()) {
                unsubscribe();
            }
        } else {
            DialogHelper.showProgressDlg(mContext, "正在加载数据");
        }
    }

这样就不会执行onError()了，不知道作者觉得对吗

**Comment by ysmintor** [comment]
```xml
12-19 15:20:45.888 W/System.err: java.net.ConnectException: Failed to connect to /192.168.115.63:8081
```
是的，有这样的问题。我这样处理的时候没有考虑到这种情况。不过没网就到onError是我的逻辑，你可以按你的方法来实现，下周有时间我研究一下这个更好我解决办法。

**Comment by ysmintor** [comment]
这个我还真不好解决，原因是确实调用了onCompleted, 但是呢又会调用有错误的处理

**Comment by ysmintor** [comment]
@Greathfs 
就按你说的来解决也很好，我引入了这部分，谢谢！
```java
if (!isUnsubscribed()) {
unsubscribe();
}
```
